# Changes here will be overwritten by Copier
_commit: 5.0.2
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: bryn.roberts@diamond.ac.uk
author_name: Bryn Roberts
component_lifecycle: production
component_owner: group:default/accelerator-controls
component_type: service
description: RF and BPM Postmortem Backend
distribution_name: cs-di-ioc-07
docker: true
docker_debug: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: rf_postmortem
pypi: false
repo_name: cs-di-ioc-07
strict_typing: false
type_checker: pyright
