apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cs-di-ioc-07
  title: cs-di-ioc-07
  description: RF and BPM Postmortem Backend
spec:
  type: service
  lifecycle: production
  owner: group:default/accelerator-controls
